baseURL = "/"
title = "The Cathay School"

contentdir          = "content"
publishdir          = "public"
enableRobotsTXT     = true
canonifyurls        = true

# Custom Parameters
[Params]
    # Social Media
    instagram       = "cathay_future"
    twitter         = "cathayfuture"
    facebook        = "CathayFuture"

    email           = "info@cathayfutureus.com"
    phone           = "1-301-978-3918"

# Main Menu Configuration

[[menu.main]]
name                   = "Home"
weight                 = 1
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "About"
weight                 = 2
identifier             = "about"

[[menu.main]]
name                   = "Welcome"
weight                 = 1
identifier             = "welcome"
url                    = "/about/welcome"
parent                 = "about"

[[menu.main]]
name                   = "Background"
weight                 = 2
identifier             = "background"
url                    = "/about/background"
parent                 = "about"

[[menu.main]]
name                   = "Curriculum"
weight                 = 3
identifier             = "curriculum"

[[menu.main]]
name                   = "About"
weight                 = 1
identifier             = "curriculum-about"
url                    = "/curriculum/about/"
parent                 = "curriculum"

[[menu.main]]
name                   = "Preschool"
weight                 = 2
identifier             = "preschool"
url                    = "/curriculum/preschool/"
parent                 = "curriculum"

[[menu.main]]
name                   = "Pre-K"
weight                 = 3
identifier             = "prek"
url                    = "/curriculum/pre-k/"
parent                 = "curriculum"

[[menu.main]]
name                   = "Admission"
weight                 = 4
identifier             = "admission"

[[menu.main]]
name                   = "Tour"
weight                 = 1
identifier             = "tour"
url                    = "/tour/"
parent                 = "admission"

[[menu.main]]
name                   = "Enroll"
weight                 = 2
identifier             = "enroll"
url                    = "/enroll/"
parent                 = "admission"

[[menu.main]]
name                   = "Tuition"
weight                 = 3
identifier             = "tuition"
url                    = "/enroll/tuition"
parent                 = "admission"

[[menu.main]]
name                   = "Calendar"
weight                 = 5
identifier             = "calendar"

[[menu.main]]
name                   = "Closings"
weight                 = 1
identifier             = "closings"
url                    = "/calendar/closings/"
parent                 = "calendar"

[[menu.main]]
name                   = "Events"
weight                 = 1
identifier             = "events"
url                    = "/calendar/events/"
parent                 = "calendar"

[[menu.main]]
name                   = "Contact"
weight                 = 6
identifier             = "contact"

[[menu.main]]
name                   = "Location"
weight                 = 1
identifier             = "location"
url                    = "/contact/location/"
parent                 = "contact"

[[menu.main]]
name                   = "Support"
weight                 = 2
identifier             = "support"
url                    = "https://shop.cathayfutureus.com/contact-support"
parent                 = "contact"