baseURL = "/"
title = "The Cathay School"

contentdir          = "content"
publishdir          = "public"
enableRobotsTXT     = true
canonifyurls        = true

# Main Menu Configuration

[[menu.main]]
name                   = "About"
weight                 = 1
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Tour"
weight                 = 2
identifier             = "tour"
url                    = "/tour/"

[[menu.main]]
name                   = "Enroll"
weight                 = 3
identifier             = "enroll"
url                    = "/enroll/"